// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1500_m_race_simulation.Data;

#nullable disable

namespace _1500_m_race_simulation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513061915_SeedRunners")]
    partial class SeedRunners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1500_m_race_simulation.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundType")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.RaceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("RunnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("RunnerId");

                    b.ToTable("RaceEntries");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.Runner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Runners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jakob Ingebrigtsen",
                            Ranking = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Josh Kerr",
                            Ranking = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yared Nuguse",
                            Ranking = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cole Hocker",
                            Ranking = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Narve Gilje Nordas",
                            Ranking = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Timothy Cheruiyot",
                            Ranking = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abel Kipsang",
                            Ranking = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Neil Gourley",
                            Ranking = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Stewart McSweyn",
                            Ranking = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Oliver Hoare",
                            Ranking = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Samuel Tefera",
                            Ranking = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "Azeddine Habz",
                            Ranking = 12
                        },
                        new
                        {
                            Id = 13,
                            Name = "Isaac Nader",
                            Ranking = 13
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mohamed Katir",
                            Ranking = 14
                        },
                        new
                        {
                            Id = 15,
                            Name = "Reynold Cheruiyot",
                            Ranking = 15
                        },
                        new
                        {
                            Id = 16,
                            Name = "George Mills",
                            Ranking = 16
                        },
                        new
                        {
                            Id = 17,
                            Name = "Mario García",
                            Ranking = 17
                        },
                        new
                        {
                            Id = 18,
                            Name = "Adel Mechaal",
                            Ranking = 18
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pietro Arese",
                            Ranking = 19
                        },
                        new
                        {
                            Id = 20,
                            Name = "Marcin Lewandowski",
                            Ranking = 20
                        },
                        new
                        {
                            Id = 21,
                            Name = "Henrik Ingebrigtsen",
                            Ranking = 21
                        },
                        new
                        {
                            Id = 22,
                            Name = "Filip Ingebrigtsen",
                            Ranking = 22
                        },
                        new
                        {
                            Id = 23,
                            Name = "Jake Wightman",
                            Ranking = 23
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hobbs Kessler",
                            Ranking = 24
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vincent Ciattei",
                            Ranking = 25
                        },
                        new
                        {
                            Id = 26,
                            Name = "Elliot Giles",
                            Ranking = 26
                        },
                        new
                        {
                            Id = 27,
                            Name = "Robert Farken",
                            Ranking = 27
                        },
                        new
                        {
                            Id = 28,
                            Name = "Kieran Lumb",
                            Ranking = 28
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cameron Myers",
                            Ranking = 29
                        },
                        new
                        {
                            Id = 30,
                            Name = "Paddy Dever",
                            Ranking = 30
                        },
                        new
                        {
                            Id = 31,
                            Name = "Luke Houser",
                            Ranking = 31
                        },
                        new
                        {
                            Id = 32,
                            Name = "Eric Holt",
                            Ranking = 32
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ben Pattison",
                            Ranking = 33
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ayanleh Souleiman",
                            Ranking = 34
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ronald Kwemoi",
                            Ranking = 35
                        },
                        new
                        {
                            Id = 36,
                            Name = "Silas Kiplagat",
                            Ranking = 36
                        },
                        new
                        {
                            Id = 37,
                            Name = "Elijah Manangoi",
                            Ranking = 37
                        },
                        new
                        {
                            Id = 38,
                            Name = "Asbel Kiprop",
                            Ranking = 38
                        },
                        new
                        {
                            Id = 39,
                            Name = "Taoufik Makhloufi",
                            Ranking = 39
                        },
                        new
                        {
                            Id = 40,
                            Name = "Matthew Centrowitz",
                            Ranking = 40
                        },
                        new
                        {
                            Id = 41,
                            Name = "Nick Willis",
                            Ranking = 41
                        },
                        new
                        {
                            Id = 42,
                            Name = "Bernard Lagat",
                            Ranking = 42
                        },
                        new
                        {
                            Id = 43,
                            Name = "Mo Farah",
                            Ranking = 43
                        },
                        new
                        {
                            Id = 44,
                            Name = "James Webb",
                            Ranking = 44
                        },
                        new
                        {
                            Id = 45,
                            Name = "Daniel Komen",
                            Ranking = 45
                        },
                        new
                        {
                            Id = 46,
                            Name = "Noah Ngeny",
                            Ranking = 46
                        },
                        new
                        {
                            Id = 47,
                            Name = "Hicham El Guerrouj",
                            Ranking = 47
                        },
                        new
                        {
                            Id = 48,
                            Name = "Noureddine Morceli",
                            Ranking = 48
                        },
                        new
                        {
                            Id = 49,
                            Name = "Sebastian Coe",
                            Ranking = 49
                        },
                        new
                        {
                            Id = 50,
                            Name = "Steve Ovett",
                            Ranking = 50
                        },
                        new
                        {
                            Id = 51,
                            Name = "Steve Cram",
                            Ranking = 51
                        },
                        new
                        {
                            Id = 52,
                            Name = "Said Aouita",
                            Ranking = 52
                        },
                        new
                        {
                            Id = 53,
                            Name = "Fermín Cacho",
                            Ranking = 53
                        },
                        new
                        {
                            Id = 54,
                            Name = "Mehdi Baala",
                            Ranking = 54
                        },
                        new
                        {
                            Id = 55,
                            Name = "Augustine Choge",
                            Ranking = 55
                        },
                        new
                        {
                            Id = 56,
                            Name = "Mekonnen Gebremedhin",
                            Ranking = 56
                        },
                        new
                        {
                            Id = 57,
                            Name = "Lopez Lomong",
                            Ranking = 57
                        },
                        new
                        {
                            Id = 58,
                            Name = "Chris O'Hare",
                            Ranking = 58
                        },
                        new
                        {
                            Id = 59,
                            Name = "Andrew Wheating",
                            Ranking = 59
                        },
                        new
                        {
                            Id = 60,
                            Name = "Leo Manzano",
                            Ranking = 60
                        },
                        new
                        {
                            Id = 61,
                            Name = "Nick Symmonds",
                            Ranking = 61
                        },
                        new
                        {
                            Id = 62,
                            Name = "Andrés Díaz",
                            Ranking = 62
                        },
                        new
                        {
                            Id = 63,
                            Name = "Brahim Boulami",
                            Ranking = 63
                        },
                        new
                        {
                            Id = 64,
                            Name = "Yusuf Saad Kamel",
                            Ranking = 64
                        },
                        new
                        {
                            Id = 65,
                            Name = "Harun Keitany",
                            Ranking = 65
                        },
                        new
                        {
                            Id = 66,
                            Name = "Soufiane El Bakkali",
                            Ranking = 66
                        });
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.Race", b =>
                {
                    b.HasOne("_1500_m_race_simulation.Models.Tournament", null)
                        .WithMany("Races")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.RaceEntry", b =>
                {
                    b.HasOne("_1500_m_race_simulation.Models.Race", null)
                        .WithMany("Entries")
                        .HasForeignKey("RaceId");

                    b.HasOne("_1500_m_race_simulation.Models.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.Race", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("_1500_m_race_simulation.Models.Tournament", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
